### ISSUE TITLE
Missing contig length

### ISSUE THREAD

**Issue by hsiaoyi0504** [rjchallis/assembly-stats#5]
After I trace the code, I see there is a missing value in contig statistics, which is at this line.

https://github.com/rjchallis/assembly-stats/blob/1f4e88e723f35845d54192d3b09095d02c8b97d8/js/circle-plot.js#L544

It should be something like this
https://github.com/rjchallis/assembly-stats/blob/1f4e88e723f35845d54192d3b09095d02c8b97d8/js/circle-plot.js#L518

**Comment by rjchallis** [comment]
Thanks for spotting this - I've pushed a commit to display the total contig length
