### ISSUE TITLE
Are contig statistics visualized ?

### ISSUE THREAD

**Issue by hsiaoyi0504** [rjchallis/assembly-stats#7]
Sorry, maybe it's a stupid question, but are contig statistics visualized ?
I can't find where are those statistics visualized in demo site.
http://content.lepbase.org/html/assembly-stats/assembly-stats.html?path=/v4/json/assemblies/&assembly=Danaus_plexippus_v3&view=circle&altAssembly=Danaus_plexippus_DanPle_1.0&altView=compare&altAssembly=Heliconius_melpomene_melpomene_Hmel2&altView=cumulative&altView=table

**Comment by hsiaoyi0504** [comment]
Oh, I just find where they are, but don't know how to interpret that for a toggle between log 10 scaffolds length count and log 10 contigs length count.

**Comment by rjchallis** [comment]
Glad you found the contig stats - all of the plot features can be toggled on or off so you can just display the statistics that you are interested in. 

Sorry, but I'm not quite sure what you mean in your comment about interpreting them. If you toggle the contig length on and the n50 and n90 overlays off then you can view the distribution of contig lengths against the distribution of scaffold lengths. These are not included in the cumulative plot but contig-level summary statistics are also shown in the table view.

**Comment by hsiaoyi0504** [comment]
Oh, I just found that there is not an actual toggle. Initially, you click the log10 contig count. It will unselect the log10 scaffolds count. Then, if you click the log10 contig count again, the purple part will disappear, but why don't you use two different color as you do for scaffolds length and contigs length (with different gray) to visualize the difference?

**Comment by rjchallis** [comment]
Ah, I see. That does make sense. 

I've updated the code so it works as you suggested - thanks for the feedback!

**Comment by hsiaoyi0504** [comment]
Fixed in rjchallis@6550bf04053b4b75f6cbaf7973fca8b7e11e57c8. Closed.
